### ISSUE TITLE
Windows 7 is not supported

### ISSUE THREAD

**Issue by Great-Anny** [bluefireteam/audioplayers#1140]
Windows 7 is not supported

**Comment by Gustl22** [comment]
Hi @Great-Anny 
IMFMediaEngine used for the Windows-Implementation is supported since [Windows 8](https://docs.microsoft.com/en-us/windows/win32/api/mfmediaengine/nn-mfmediaengine-imfmediaengine)!

Also even Microsoft [doesn't support](https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962) Windows 7 anymore!
So for the security of your PC, just upgrade to Windows 10!

**Comment by erickzanardo** [comment]
Windows 7 isn't supported anymore by Microsoft. We don't plan on adding support to it.

**Comment by kirill-21** [comment]
So if you go to the source code of windows plugin implementation and change this method **MFPutWorkItem** to:
```c++
typedef HRESULT (WINAPI* _MFPutWorkItem2)(DWORD, LONG, IMFAsyncCallback*, IUnknown*);

inline void MFPutWorkItem(std::function<void()> callback)
{
    winrt::com_ptr<MFWorkItem> workItem = winrt::make_self<MFWorkItem>(callback);
    HINSTANCE sound_library = LoadLibrary(L"MFPLat.dll");
    if(!sound_library) throw;

    _MFPutWorkItem2 method = (_MFPutWorkItem2)GetProcAddress(sound_library, "MFPutWorkItem2");
    if(!method) {
        FreeLibrary(sound_library);
        throw;
    }

    HRESULT result = method(workItem->GetQueue(), 0, workItem.get(), nullptr);
    THROW_IF_FAILED(result);
}
```

(also these headers must me incuded)
```c++
#include <Windows.h>
#include <Mfidl.h>
```

you'll get rid of this error
![image](https://user-images.githubusercontent.com/63228361/226275580-8a4ae7df-f611-4479-8991-34058f546b94.png)


But, this package also requires a lot of other libraries to be present near the executable of your app:
![image](https://user-images.githubusercontent.com/63228361/226279215-621c73dc-afc1-4b5b-889e-0a37225a2954.png)
If you add them, the app will crash with **0xc000007b** error. Right now i have no idea how to fix that. Maybe it's better to migrate from platform's methodchannel to win32 package and do everything with ffi-api.
