### ISSUE TITLE
I cann't  find `onPlayerError` method  in `1.0.x`

### ISSUE THREAD

**Issue by doutuifei** [bluefireteam/audioplayers#1179]
I cann't  find `onPlayerError` method  in `1.0.x` version.
What's the alternative?

**Comment by memisibram** [comment]
I have a list of radios and there are radios whose broadcast is temporarily stopped, when I choose one of them, the last selected broadcast starts to play. The console throws an error, but it is not caught with **onPlayerError** because for onPlayerError ""**The getter 'onPlayerError' isn't defined for the type 'AudioPlayer**'"" There is a warning and there seems to be no alternative. Someone maybe knows something.

^1.0.1 version

**Comment by luanpotter** [comment]
I removed this stream because it was actually never used. We now have a `Logger` infrastructure (+ exceptions) for reporting errors.

**Comment by Purus** [comment]
Logging an error and handling an error are different. Hope this stream is introduced back. Thanks in advance.
