### ISSUE TITLE
docs:  more descriptive codes and information in Getting Started tutorial for AudioCache

### ISSUE THREAD

**Issue by Hallcoder** [bluefireteam/audioplayers#1256]
## Checklist
- [x] I made sure that the feature I am proposing doesn't already exist

## Proposal / Solution

<details>
  <summary>Example Code</summary>

  

  ```dart
  void main() {
  }
  ```
</details>

## Platforms

Affected Platforms:

**Comment by spydon** [comment]
Can you be a bit more descriptive, what is it that you think is missing from the getting started page? And does that information exist in the example app?

**Comment by Hallcoder** [comment]
I mean , informing and emphasize that one need the audio cache when working
with local audio files

**Comment by spydon** [comment]
I think that it is pretty clearly explained here that you need the audio cache when working with local files?
https://github.com/bluefireteam/audioplayers/blob/main/getting_started.md#audiocache

> In order to play Local Assets, you must use the AudioCache class. AudioCache is not available for Flutter Web.
> 
> Flutter does not provide an easy way to play audio on your assets, but this class helps a lot. It actually copies the asset to a temporary folder in the device, where it is then played as a Local File.
> 
> It works as a cache because it keeps track of the copied files so that you can replay them without delay.

**Comment by Gustl22** [comment]
I agree it could be a bit more clear, for which sources you need to use the AudioCache, and what it cannot do. In fact it is only relevant for `AssetSource`.

**Comment by gadishimwe** [comment]
Hi @Gustl22,
Why can't the use of `AudioCache` from the Getting Started tutorial be removed or rephrased as it's mentioned [here](https://github.com/bluefireteam/audioplayers/blob/main/migration_guide.md) in the Migration guide that it's dead and normally shouldn't be used by end users?
Because in the tutorial, it sounds like we must use it for local files("In order to play Local Assets, you must use the AudioCache class") which I think is misleading. Thanks

**Comment by Gustl22** [comment]
Yes, it is misleading, this could be adapted. Even web uses the AudioCache class, but differently ...
