### ISSUE TITLE
feat: how to handle platform error?

### ISSUE THREAD

**Issue by badboy-tian** [bluefireteam/audioplayers#1266]
```
 audioPlayer.onPlayerError.listen((msg) {
}

no this function?
```

**Comment by Gustl22** [comment]
It's currently broken. Will be fixed soon via: #1254

**Comment by Gustl22** [comment]
Ah I see, you mean to handle the error programmatically. I think currently this is not possible, but would be a good addition. The error are only logged.

**Comment by Gustl22** [comment]
Ideally the library should never throw an error. So this would be something we need to catch in the lib or don't even let it go that far. 
I would propose to check if the file exists, before loading it to audioplayers.

**Comment by Ejazullah579** [comment]
well yes to begin with i do the same. if file not found then he has to download it otherwise reloads the file. I carried the following at the runtime. so like it was ready to load then i got back to explorer and deleted that file and then tried playing that file. Though this type of case is rare but its just a precaution for headsup
